package org.zhb.ssm.crud.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Department {
    private Integer deptId;
    private String deptName;
}

/**
 * 以下是GDB自动生成的DepartmentBean，已全部注释掉
 *
 *
 */
/*public class Department {
    *//**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.dept_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*
    private Integer deptId;

    *//**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.dept_name
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*
    private String deptName;*/

/*    *//**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.dept_id
     *
     * @return the value of tbl_dept.dept_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*
    public Integer getDeptId() {
        return deptId;
    }

    *//**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.dept_id
     *
     * @param deptId the value for tbl_dept.dept_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    *//**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.dept_name
     *
     * @return the value of tbl_dept.dept_name
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*
    public String getDeptName() {
        return deptName;
    }

    *//**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.dept_name
     *
     * @param deptName the value for tbl_dept.dept_name
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }*/
/*
}*/
