package org.zhb.ssm.crud.bean;


import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Employee {
    private Integer empId;

    //用户名限制
    @Pattern(regexp="(^[a-zA-Z0-9_-]{6,16}$)|(^[\u2E80-\u9FFF]{2,5})",
            message="合法用户名:6-16位字母数字组合或2-5位中文")
    private String empName;

    private String gender;

    //邮箱格式限制
    @Pattern(regexp="^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$",
            message="邮箱名格式不正确")
    private String email;

    private Integer dId;

    //查员工的同时，一并查询部门信息
    private Department department;

    //不包含Department的构造器
    public Employee(Integer empId, String empName, String gender, String email, Integer dId) {
        this.empId = empId;
        this.empName = empName;
        this.gender = gender;
        this.email = email;
        this.dId = dId;
    }
}

/**
 * 以下是MBG逆向生成的EmployeeBean，已全部注释掉
 */

/*
public class Employee {
    */
/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    private Integer empId;

    */
/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_name
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    private String empName;

    */
/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.gender
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    private String gender;

    */
/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.email
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    private String email;

    */
/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.d_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    private Integer dId;

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_id
     *
     * @return the value of tbl_emp.emp_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public Integer getEmpId() {
        return empId;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_id
     *
     * @param empId the value for tbl_emp.emp_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_name
     *
     * @return the value of tbl_emp.emp_name
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public String getEmpName() {
        return empName;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_name
     *
     * @param empName the value for tbl_emp.emp_name
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.gender
     *
     * @return the value of tbl_emp.gender
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public String getGender() {
        return gender;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.gender
     *
     * @param gender the value for tbl_emp.gender
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.email
     *
     * @return the value of tbl_emp.email
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public String getEmail() {
        return email;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.email
     *
     * @param email the value for tbl_emp.email
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.d_id
     *
     * @return the value of tbl_emp.d_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public Integer getdId() {
        return dId;
    }

    */
/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.d_id
     *
     * @param dId the value for tbl_emp.d_id
     *
     * @mbg.generated Tue Mar 15 16:40:09 CST 2022
     *//*

    public void setdId(Integer dId) {
        this.dId = dId;
    }
}*/
